# Generated by Django 6.0.7 on 2026-07-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReviewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('projection_seq', models.BigIntegerField(default=0)),
                ('projection_event_id', models.CharField(blank=True, default='', max_length=64)),
                ('projection_updated_at', models.DateTimeField(auto_now=True)),
                ('rating_avg', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
